/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsCategoryIdRouteImport } from './routes/products.$categoryId'
import { Route as ProductsCategoryIdIndexRouteImport } from './routes/products.$categoryId.index'
import { Route as ProductsCategoryIdProductIdRouteImport } from './routes/products.$categoryId.$productId'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCategoryIdRoute = ProductsCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCategoryIdIndexRoute = ProductsCategoryIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsCategoryIdRoute,
} as any)
const ProductsCategoryIdProductIdRoute =
  ProductsCategoryIdProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => ProductsCategoryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/products/$categoryId': typeof ProductsCategoryIdRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$categoryId/$productId': typeof ProductsCategoryIdProductIdRoute
  '/products/$categoryId/': typeof ProductsCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/products': typeof ProductsIndexRoute
  '/products/$categoryId/$productId': typeof ProductsCategoryIdProductIdRoute
  '/products/$categoryId': typeof ProductsCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/products/$categoryId': typeof ProductsCategoryIdRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$categoryId/$productId': typeof ProductsCategoryIdProductIdRoute
  '/products/$categoryId/': typeof ProductsCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/quote'
    | '/services'
    | '/products/$categoryId'
    | '/products/'
    | '/products/$categoryId/$productId'
    | '/products/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/quote'
    | '/services'
    | '/products'
    | '/products/$categoryId/$productId'
    | '/products/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/quote'
    | '/services'
    | '/products/$categoryId'
    | '/products/'
    | '/products/$categoryId/$productId'
    | '/products/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$categoryId': {
      id: '/products/$categoryId'
      path: '/$categoryId'
      fullPath: '/products/$categoryId'
      preLoaderRoute: typeof ProductsCategoryIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$categoryId/': {
      id: '/products/$categoryId/'
      path: '/'
      fullPath: '/products/$categoryId/'
      preLoaderRoute: typeof ProductsCategoryIdIndexRouteImport
      parentRoute: typeof ProductsCategoryIdRoute
    }
    '/products/$categoryId/$productId': {
      id: '/products/$categoryId/$productId'
      path: '/$productId'
      fullPath: '/products/$categoryId/$productId'
      preLoaderRoute: typeof ProductsCategoryIdProductIdRouteImport
      parentRoute: typeof ProductsCategoryIdRoute
    }
  }
}

interface ProductsCategoryIdRouteChildren {
  ProductsCategoryIdProductIdRoute: typeof ProductsCategoryIdProductIdRoute
  ProductsCategoryIdIndexRoute: typeof ProductsCategoryIdIndexRoute
}

const ProductsCategoryIdRouteChildren: ProductsCategoryIdRouteChildren = {
  ProductsCategoryIdProductIdRoute: ProductsCategoryIdProductIdRoute,
  ProductsCategoryIdIndexRoute: ProductsCategoryIdIndexRoute,
}

const ProductsCategoryIdRouteWithChildren =
  ProductsCategoryIdRoute._addFileChildren(ProductsCategoryIdRouteChildren)

interface ProductsRouteChildren {
  ProductsCategoryIdRoute: typeof ProductsCategoryIdRouteWithChildren
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsCategoryIdRoute: ProductsCategoryIdRouteWithChildren,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRouteWithChildren,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
